### PR TITLE
refactor(eslint): use yaml as configuration file extension

### PR DESCRIPTION
**Pull request by antleblanc**
### Description of the Change

7604fb8- refactor(eslint): use yaml as configuration file extension

/cc @blaryjp

### CODE REVIEW

**Review by jpatovh — COMMENTED** [review]
plz rename in templates/ too :)

**Comment by antleblanc** [comment]
@blaryjp I updated `templates/.eslintrc.yaml` as well.

**Comment by jleveugle** [comment]
Hello @antleblanc,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Comment by jleveugle** [comment]
Hello @antleblanc,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Comment by jleveugle** [comment]
Hello @antleblanc,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Comment by jleveugle** [comment]
Hello @antleblanc,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Pull request closed without merging**
