### PR TITLE
feat(gulp plugins): use gulp-load-plugins dependency

### PR DESCRIPTION
**Pull request by antleblanc**
@blaryjp feel free to tell me if you find this **useful**.

### CODE REVIEW

**Comment by antleblanc** [comment]
ping @blaryjp 🍺

**Comment by jpatovh** [comment]
Hi.

Did you validates your changes ? All the cases ?

Thx

**Comment by antleblanc** [comment]
Yes I did!
So, what you're meaning here is if that each plugins/tasks went well, right?

All tests has been doing in a micro environment and you're probably in a better position than I to achieve more advanced tests 😃.

Hope it helps you! 💋

**Comment by jleveugle** [comment]
Hello @antleblanc,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Comment by jleveugle** [comment]
Hello @antleblanc,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Comment by antleblanc** [comment]
I close this pull request due to inactivity.

**Pull request closed without merging**
